### ISSUE TITLE
Synchronize the reader for using multiple threads

### ISSUE THREAD

**Issue by m273d15** [BenReissaus/ESB-DataSender#8]
The method `getLine` in class `DataReader` is currently not synchronised, therefore the usage of more than one thread could cause problems.

**Comment by BenReissaus** [comment]
This is probably not necessary anymore. The KafkaProducer class internally batches messages together before it sends them in a Background I/O Thread. We therefore only need one DataProducerThread which calls send() on the producer. The rest is handled by the KafkaProducer. 
See issue #6 for details.
